package flash.utils {
	[native(cls="ShellPosixClass", instance="ShellPosixObject", methods="auto")]
	CONFIG::VMCFG_ALCHEMY_POSIX
	public class ShellPosix implements IKernel {
	public native static function getAppPath():String;

		public native function fork(errnoPtr:int):int;
		public native function read(A_fd:int, A_buf:int, A_nbyte:int, errnoPtr:int):int;
		public native function write(A_fd:int, A_buf:int, A_nbyte:int, errnoPtr:int):int;
		public native function open(A_path:int, A_flags:int, A_mode:int, errnoPtr:int):int;
		public native function close(A_fd:int, errnoPtr:int):int;
		public native function wait4(A_pid:int, A_status:int, A_options:int, A_rusage:int, errnoPtr:int):int;
		public native function link(A_path:int, A_linkpath:int, errnoPtr:int):int;
		public native function unlink(A_path:int, errnoPtr:int):int;
		public native function chdir(A_path:int, errnoPtr:int):int;
		public native function fchdir(A_fd:int, errnoPtr:int):int;
		public native function chmod(A_path:int, A_mode:int, errnoPtr:int):int;
		public native function chown(A_path:int, A_uid:int, A_gid:int, errnoPtr:int):int;
		public native function lseek(A_fd:int, A_offset_high:int, A_offset_low:int, A_whence:int, errnoPtr:int):Object;
		public native function getpid(errnoPtr:int):int;
		public native function setuid(A_uid:int, errnoPtr:int):int;
		public native function getuid(errnoPtr:int):int;
		public native function geteuid(errnoPtr:int):int;
		public native function access(A_path:int, A_flags:int, errnoPtr:int):int;
		public native function sync(errnoPtr:int):void;
		public native function kill(A_pid:int, A_signum:int, errnoPtr:int):int;
		public native function getppid(errnoPtr:int):int;
		public native function dup(A_fd:int, errnoPtr:int):int;
		public native function pipe(A_fildes:int, errnoPtr:int):int;
		public native function getegid(errnoPtr:int):int;
		public native function getgid(errnoPtr:int):int;
		public native function ioctl(A_fd:int, A_com:int, A_data:int, errnoPtr:int):int;
		public native function revoke(A_path:int, errnoPtr:int):int;
		public native function symlink(A_path:int, A_link:int, errnoPtr:int):int;
		public native function umask(A_newmask:int, errnoPtr:int):int;
		public native function chroot(A_path:int, errnoPtr:int):int;
		public native function msync(A_addr:int, A_len:int, A_flags:int, errnoPtr:int):int;
		public native function vfork(errnoPtr:int):int;
		public native function getgroups(A_gidsetsize:int, A_gidset:int, errnoPtr:int):int;
		public native function setgroups(A_gidsetsize:int, A_gidset:int, errnoPtr:int):int;
		public native function getpgrp(errnoPtr:int):int;
		public native function setpgid(A_pid:int, A_pgid:int, errnoPtr:int):int;
		public native function getdtablesize(errnoPtr:int):int;
		public native function dup2(A_from:int, A_to:int, errnoPtr:int):int;
		public native function fcntl(A_fd:int, A_cmd:int, A_arg:int, errnoPtr:int):int;
		public native function fsync(A_fd:int, errnoPtr:int):int;
		public native function setpriority(A_which:int, A_who:int, A_prio:int, errnoPtr:int):int;
		public native function socket(A_domain:int, A_type:int, A_protocol:int, errnoPtr:int):int;
		public native function getpriority(A_which:int, A_who:int, errnoPtr:int):int;
		public native function setsockopt(A_s:int, A_level:int, A_name:int, A_val:int, A_valsize:int, errnoPtr:int):int;
		public native function listen(A_s:int, A_backlog:int, errnoPtr:int):int;
		public native function sigsuspend(A_mask:int, errnoPtr:int):int;
		public native function getrusage(A_who:int, A_rusage:int, errnoPtr:int):int;
		public native function getsockopt(A_s:int, A_level:int, A_name:int, A_val:int, A_avalsize:int, errnoPtr:int):int;
		public native function readv(A_fd:int, A_iovp:int, A_iovcnt:int, errnoPtr:int):int;
		public native function writev(A_fd:int, A_iovp:int, A_iovcnt:int, errnoPtr:int):int;
		public native function fchown(A_fd:int, A_uid:int, A_gid:int, errnoPtr:int):int;
		public native function fchmod(A_fd:int, A_mode:int, errnoPtr:int):int;
		public native function setreuid(A_ruid:int, A_euid:int, errnoPtr:int):int;
		public native function setregid(A_rgid:int, A_egid:int, errnoPtr:int):int;
		public native function rename(A_from:int, A_to:int, errnoPtr:int):int;
		public native function mkfifo(A_path:int, A_mode:int, errnoPtr:int):int;
		public native function shutdown(A_s:int, A_how:int, errnoPtr:int):int;
		public native function socketpair(A_domain:int, A_type:int, A_protocol:int, A_rsv:int, errnoPtr:int):int;
		public native function mkdir(A_path:int, A_mode:int, errnoPtr:int):int;
		public native function rmdir(A_path:int, errnoPtr:int):int;
		public native function setsid(errnoPtr:int):int;
		public native function getdirentries(A_fd:int, A_buf:int, A_count:int, A_basep:int, errnoPtr:int):int;
		public native function setgid(A_gid:int, errnoPtr:int):int;
		public native function setegid(A_egid:int, errnoPtr:int):int;
		public native function seteuid(A_euid:int, errnoPtr:int):int;
		public native function stat(A_path:int, A_ub:int, errnoPtr:int):int;
		public native function fstat(A_fd:int, A_sb:int, errnoPtr:int):int;
		public native function lstat(A_path:int, A_ub:int, errnoPtr:int):int;
		public native function pathconf(A_path:int, A_name:int, errnoPtr:int):int;
		public native function fpathconf(A_fd:int, A_name:int, errnoPtr:int):int;
		public native function getpgid(A_pid:int, errnoPtr:int):int;
		public native function semget(A_key:int, A_nsems:int, A_semflg:int, errnoPtr:int):int;
		public native function msgget(A_key:int, A_msgflg:int, errnoPtr:int):int;
		public native function msgsnd(A_msqid:int, A_msgp:int, A_msgsz:int, A_msgflg:int, errnoPtr:int):int;
		public native function msgrcv(A_msqid:int, A_msgp:int, A_msgsz:int, A_msgtyp:int, A_msgflg:int, errnoPtr:int):int;
		public native function shmdt(A_shmaddr:int, errnoPtr:int):int;
		public native function shmget(A_key:int, A_size:int, A_shmflg:int, errnoPtr:int):int;
		public native function clock_gettime(A_clock_id:int, A_tp:int, errnoPtr:int):int;
		public native function nanosleep(A_rqtp:int, A_rmtp:int, errnoPtr:int):int;
		public native function lchown(A_path:int, A_uid:int, A_gid:int, errnoPtr:int):int;
		public native function getsid(A_pid:int, errnoPtr:int):int;
		public native function sched_yield(errnoPtr:int):int;
		public native function sched_get_priority_max(A_policy:int, errnoPtr:int):int;
		public native function sched_get_priority_min(A_policy:int, errnoPtr:int):int;
		public native function sigprocmask(A_how:int, A_set:int, A_oset:int, errnoPtr:int):int;
		public native function sigpending(A_set:int, errnoPtr:int):int;
		public native function sigwait(A_set:int, A_sig:int, errnoPtr:int):int;
		public native function shm_unlink(A_path:int, errnoPtr:int):int;
		public native function pselect(A_nd:int, A_in:int, A_ou:int, A_ex:int, A_ts:int, A_sm:int, errnoPtr:int):int;
	}
}
