void endLine();

////

int lexicalKeywords0(int as);
int lexicalKeywords1(int extends);
int lexicalKeywords2(int finally);
int lexicalKeywords3(int function);
int lexicalKeywords4(int implements);
int lexicalKeywords5(int import);
int lexicalKeywords6(int in);
int lexicalKeywords7(int instanceof);
int lexicalKeywords8(int interface);
int lexicalKeywords9(int internal);
int lexicalKeywords10(int is);
int lexicalKeywords11(int native);
int lexicalKeywords12(int null);
int lexicalKeywords13(int package);
int lexicalKeywords14(int super);
int lexicalKeywords15(int to);
int lexicalKeywords16(int use);
int lexicalKeywords17(int var);
int lexicalKeywords18(int with);
int syntacticKeywords0(int each);
int syntacticKeywords1(int get);
int syntacticKeywords2(int set);
int syntacticKeywords3(int include);
int syntacticKeywords4(int dynamic);
int syntacticKeywords5(int final);
int syntacticKeywords6(int native);
int syntacticKeywords7(int override);
int futureReservedWords0(int abstract);
int futureReservedWords1(int boolean);
int futureReservedWords2(int byte);
int futureReservedWords3(int cast);
int futureReservedWords4(int debugger);
int futureReservedWords5(int intrinsic);
int futureReservedWords6(int prototype);
int futureReservedWords7(int synchronized);
int futureReservedWords8(int throws);
int futureReservedWords9(int to);
int futureReservedWords10(int transient);
int futureReservedWords11(int type);