#! /bin/sh

# Make sure we're POSIX
if [ "$PKG_CONFIG_SHELL_IS_POSIX" != "1" ]; then
    PKG_CONFIG_SHELL_IS_POSIX=1 PATH=`getconf PATH` exec sh $0 "$@"
fi

set -e

. ${srcdir}/common

ARGS="--static --libs simple"
RESULT="-lsimple -lm"

run_test
