#===-- Makefile.common - Common make rules for LLVM --------*- Makefile -*--===#
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
#===------------------------------------------------------------------------===#

#
# Include the configuration file
#
include $(LEVEL)/Makefile.config


#
# Include LLVM's Master Makefile.
#
include $(PROJ_SRC_ROOT)/Makefile.rules
