# Copyright (c) 2011 David E O'Brien
# $FreeBSD: release/9.1.0/lib/libedit/edit/readline/Makefile 237985 2012-07-02 09:35:28Z obrien $

INCS=	readline.h history.h tilde.h

INCSDIR= ${INCLUDEDIR}/edit/readline

.include <bsd.lib.mk>
