# SingleSource/UnitTests/ObjC++/Makefile
LEVEL = ../../..
include $(LEVEL)/Makefile.config

DIRS :=

LDFLAGS += -lstdc++ -lobjc -framework Foundation
PROGRAM_REQUIRED_TO_EXIT_OK := 1
include $(LEVEL)/SingleSource/Makefile.singlesrc
