# $FreeBSD: release/9.1.0/include/xlocale/Makefile 231673 2012-02-14 12:03:23Z theraven $ 

NO_OBJ=
INCS=	_ctype.h _inttypes.h _langinfo.h _locale.h _monetary.h _stdio.h\
	_stdlib.h _string.h _time.h _wchar.h
INCSDIR=${INCLUDEDIR}/xlocale

.include <bsd.prog.mk>
