LEVEL = ../../../
PROG = MultipleResults
LDFLAGS =

include $(LEVEL)/Makefile.config

EXTRA_TEST_RESULTS_FILE := $(PROJ_OBJ_DIR)/Output/MultipleResults.extra-results.txt
RUN_OPTIONS := $(EXTRA_TEST_RESULTS_FILE)

include ../../Makefile.multisrc
