#
# =BEGIN MIT LICENSE
# 
# The MIT License (MIT)
#
# Copyright (c) 2014 The CrossBridge Team
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# 
# =END MIT LICENSE
#

all: check
	@echo "-------- Example SDL Lessons --------"
	@echo "Downloading examples ..."
	@curl -L -o lesson01.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson01 && unzip lesson01.zip
	@curl -L -o lesson02.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson02 && unzip lesson02.zip
	@curl -L -o lesson03.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson03 && unzip lesson03.zip
	@curl -L -o lesson04.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson04 && unzip lesson04.zip
	@curl -L -o lesson05.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson05 && unzip lesson05.zip
	@curl -L -o lesson06.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson06 && unzip lesson06.zip
	@curl -L -o lesson07.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson07 && unzip lesson07.zip
	@curl -L -o lesson08.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson08 && unzip lesson08.zip
	@curl -L -o lesson09.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson09 && unzip lesson09.zip
	@curl -L -o lesson10.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson10 && unzip lesson10.zip
	@curl -L -o lesson11.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson11 && unzip lesson11.zip
	@curl -L -o lesson12.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson12 && unzip lesson12.zip
	@curl -L -o lesson13.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson13 && unzip lesson13.zip
	@curl -L -o lesson14.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson14 && unzip lesson14.zip
	@curl -L -o lesson15.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson15 && unzip lesson15.zip
	@curl -L -o lesson16.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson16 && unzip lesson16.zip
	@curl -L -o lesson17.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson17 && unzip lesson17.zip
	@curl -L -o lesson18.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson18 && unzip lesson18.zip
	@curl -L -o lesson19.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson19 && unzip lesson19.zip
	@curl -L -o lesson20.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson20 && unzip lesson20.zip
	@curl -L -o lesson21.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson21 && unzip lesson21.zip
	@curl -L -o lesson22.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson22 && unzip lesson22.zip
	@curl -L -o lesson23.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson23 && unzip lesson23.zip
	@curl -L -o lesson24.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson24 && unzip lesson24.zip
	@curl -L -o lesson25.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson25 && unzip lesson25.zip
	@curl -L -o lesson26.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson26 && unzip lesson26.zip
	@curl -L -o lesson27.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson27 && unzip lesson27.zip
	@curl -L -o lesson28.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson28 && unzip lesson28.zip
	@curl -L -o lesson29.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson29 && unzip lesson29.zip
	@curl -L -o lesson30.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson30 && unzip lesson30.zip
	@curl -L -o lesson31.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson31 && unzip lesson31.zip
	@curl -L -o lesson32.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson32 && unzip lesson32.zip
	@curl -L -o lesson33.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson33 && unzip lesson33.zip
	@curl -L -o lesson34.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson34 && unzip lesson34.zip
	@curl -L -o lesson35.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson35 && unzip lesson35.zip
	@curl -L -o lesson36.zip http://lazyfoo.net/downloads/index.php?file=SDLTut_lesson36 && unzip lesson36.zip

include ../Makefile.common

clean:
	@rm -fr lesson*
	@rm -f *.swf *.swc *.bc *.abc *.exe *.zip
