/* This testcase tests a problem that occurred due to the way call nodes are 
 * generated by llvmgcc.
 */

#include <stdio.h>
#include <stdlib.h>

int main() {
    unsigned char *validate_array;

    validate_array = (unsigned char *)malloc(64);
    if (validate_array == 0) {
	printf("FAILURE!\n");
	exit(1);
    }

    printf("SUCCESS\n");
    return 0;
}
