/* this file is automatically generated by 'make'; do not edit! */
#ifndef DEFS_H
# define  RCSMAKEID "@(#)$Id: defs.h 12720 2004-04-06 20:25:22Z criswell $"
# define  KIMWITUCOPYRIGHT "@(#)$Author: criswell $"
# define  KC_USE_STAT
# define  KIMWITURELEASE "@(#)RELEASE VERSION 2.3.8"
# define  KIMWITUVERSIONSTRING "2.3.8"
# define  METAKIMWITUVERSIONMAJOR 2
# define  METAKIMWITUVERSIONMINOR 3
# define  METAKIMWITUVERSIONMICRO 8
#endif /* DEFS_H */
