/* DO NOT EDIT THIS FILE!  It was generated by utils/apivergen.abc. */

/* This Source Code Form is subject to the terms of the Mozilla Public * License, v. 2.0. If a copy of the MPL was not distributed with this * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
CONFIG const AIR_1_0 = 661;
CONFIG const FP_10_0 = 662;
CONFIG const AIR_1_5 = 663;
CONFIG const AIR_1_5_1 = 664;
CONFIG const FP_10_0_32 = 665;
CONFIG const AIR_1_5_2 = 666;
CONFIG const FP_10_1 = 667;
CONFIG const AIR_2_0 = 668;
CONFIG const AIR_2_5 = 669;
CONFIG const FP_10_2 = 670;
CONFIG const AIR_2_6 = 671;
CONFIG const SWF_12 = 672;
CONFIG const AIR_2_7 = 673;
CONFIG const SWF_13 = 674;
CONFIG const AIR_3_0 = 675;
CONFIG const SWF_14 = 676;
CONFIG const AIR_3_1 = 677;
CONFIG const SWF_15 = 678;
CONFIG const AIR_3_2 = 679;
CONFIG const SWF_16 = 680;
CONFIG const AIR_3_3 = 681;
CONFIG const SWF_17 = 682;
CONFIG const AIR_3_4 = 683;
CONFIG const SWF_18 = 684;
CONFIG const AIR_3_5 = 685;
CONFIG const SWF_19 = 686;
CONFIG const AIR_3_6 = 687;
CONFIG const VM_INTERNAL = 688;
