/* DO NOT EDIT THIS FILE!  It was generated by utils/apivergen.abc. */

/* This Source Code Form is subject to the terms of the Mozilla Public * License, v. 2.0. If a copy of the MPL was not distributed with this * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
#ifndef api_versions_H_
#define api_versions_H_

namespace avmplus {

enum ApiVersionSeries {
    kApiVersionSeries_AIR,
    kApiVersionSeries_FP
};

enum {
    kApiVersionSeries_count = 2
};

enum ApiVersion {
    kApiVersion_VM_ALLVERSIONS = 0,
    kApiVersion_AIR_1_0 = 1,
    kApiVersion_FP_10_0 = 2,
    kApiVersion_AIR_1_5 = 3,
    kApiVersion_AIR_1_5_1 = 4,
    kApiVersion_FP_10_0_32 = 5,
    kApiVersion_AIR_1_5_2 = 6,
    kApiVersion_FP_10_1 = 7,
    kApiVersion_AIR_2_0 = 8,
    kApiVersion_AIR_2_5 = 9,
    kApiVersion_FP_10_2 = 10,
    kApiVersion_AIR_2_6 = 11,
    kApiVersion_SWF_12 = 12,
    kApiVersion_AIR_2_7 = 13,
    kApiVersion_SWF_13 = 14,
    kApiVersion_AIR_3_0 = 15,
    kApiVersion_SWF_14 = 16,
    kApiVersion_AIR_3_1 = 17,
    kApiVersion_SWF_15 = 18,
    kApiVersion_AIR_3_2 = 19,
    kApiVersion_SWF_16 = 20,
    kApiVersion_AIR_3_3 = 21,
    kApiVersion_SWF_17 = 22,
    kApiVersion_AIR_3_4 = 23,
    kApiVersion_SWF_18 = 24,
    kApiVersion_AIR_3_5 = 25,
    kApiVersion_SWF_19 = 26,
    kApiVersion_AIR_3_6 = 27,
    kApiVersion_VM_INTERNAL = 28
};

enum {
    kApiVersion_count = 29
};

extern const char* const kApiVersionNames[kApiVersion_count];
extern uint32_t const kApiVersionSeriesMembership[kApiVersion_count];
extern ApiVersion const kApiVersionSeriesTransfer[kApiVersion_count][kApiVersionSeries_count];
extern ApiVersion const kApiVersionFirst[kApiVersionSeries_count];
extern ApiVersion const kApiVersionLatest[kApiVersionSeries_count];

}
#endif // api_versions_H_
